version: '3'

services: 
  web-application:
    build: .
    ports: 
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    container_name: web-application
    networks:
      - rede
networks:
  rede:
    driver: bridge